### ISSUE TITLE
feat: 提供使用第三方小程序组件库的解决方案

### ISSUE THREAD

**Issue by HyperLife1119** [wszgrcy/angular-miniprogram#3]
#### 功能需求
开发者通常需要复用小程序现有的一些组件库，例如：https://vant-contrib.gitee.io/vant-weapp/#/home
这些组件库是使用小程序原生开发的，可能需要提供一些选项设置或者自动识别，编译这些第三方的小程序组件库。
解决此问题显得尤为重要，这可以让开发者借助这些第三方组件库进行快速开发。

**Comment by HCenggel** [comment]
开发组件库的工作量太大了

**Comment by HCenggel** [comment]
如果考虑UI，ionic倒是有一个

**Comment by wszgrcy** [comment]
第一版暂时不支持
考虑到ng有很多现成的组件库,所以先尽量将语法支持完整,最后进行兼容性修改

**Comment by HyperLife1119** [comment]
小程序有很多限制，例如不支持动态插入节点等等，现成的 Web 组件库不能很好的在小程序上运行。

**Comment by HyperLife1119** [comment]
现有的 Web 组件库并不能很好的在小程序上运作...

**Comment by zuohuadong** [comment]
angular + taro 有没有可行性，这样的话，不用考虑兼容支付宝、百度小程序、头条小程序这些了。。。。

**Comment by wszgrcy** [comment]
已经实现,可以通过ng library的方式构建小程序上的组件库,只是部分逻辑不兼容,需要自行设计
