### ISSUE TITLE
Angular 17 support

### ISSUE THREAD

**Issue by CapoD** [wszgrcy/angular-miniprogram#52]
Hi,

I stumbled upon your project and find it very impressing. We are currently trying to figure out a way to port our Angular 17 app to WeChat.

Do you guys plan to upgrade your project to Angular 17?

Btw.: If you guys are offering consultancy services, please let me know.

**Comment by wszgrcy** [comment]
> Hi,
> 
> I stumbled upon your project and find it very impressing. We are currently trying to figure out a way to port our Angular 17 app to WeChat.
> 
> Do you guys plan to upgrade your project to Angular 17?
> 
> Btw.: If you guys are offering consultancy services, please let me know.

Version 1.5.2 has been released, based on Angular 17.3.1

**Comment by Lyfei** [comment]
真有外国人做国内市场啊
